### ISSUE TITLE
Separate wiki by platform types , i.e. APM, PixHawk, Linux

### ISSUE THREAD

**Issue by lvale** [diydrones/ardupilot_wordpress_sources#1]
Currently the wiki has all platforms mixed, either by having separate articles for APM and for PixHawk - example are:

http://copter.ardupilot.com/wiki/common-optional-hardware/common-telemetry-landingpage/connecting-your-rc-input-and-motors/

http://copter.ardupilot.com/wiki/common-pixhawk-wiring-and-quick-start/

Or articles that don't refer to which platform the feature is applied like:

http://copter.ardupilot.com/wiki/configuration/ekf-inav-failsafe/

Or pages that mix instructions for APM and PixHawk like

http://copter.ardupilot.com/wiki/common-optional-hardware/common-rangefinder-landingpage/common-rangefinder-maxbotix-analog/

For the sake of clarity, I believe these should have a top level filter/division to enable users to see only the applicable articles to each platform, APM/PixHawk/Linux/...etc...while maintaining the non platform specific articles on each tree repeated, like what is done now for plane/copter/rover, etc.

So the top level would be Copter/PixHawk, or Copter/APM, or Plane/PixHawk Plane/APM.

When new platforms appear the existing structure would be able to cope with them, and create a specific tree to that platform.

**Comment by hamishwillee** [comment]
Hi @lvale 

Thanks for your post - much appreciated. Just FYI the right place for [wiki issues is here](https://github.com/diydrones/ardupilot-wiki-issue-tracker/issues) - this repo just holds source to make it easier for Chinese sites to translate our content.

Yes, the organisation is a bit haphazard. I am in broad agreement that the sections under [Assembly Instructions](http://copter.ardupilot.com/wiki/initial-setup/assembly-instructions/) should be better organised by platform - and this would also help us recognise where we are missing material on different platforms. This is something I hope to get to as I continue moving to just one TOC (a tedious process that I am doing in parallel with work on DroneKit).

This will not be something as rigid as you are describing because we have a lot of topics where the flight controller is largely irrelevant or has lot of common behaviour with only small differences for flight controller. I really don't think it is smart to duplicate the content, and if you split the content and link to the controller-specific material then the instructions can become harder to follow. 

What I would like to do is:
- add metadata (tags?) to mark up what documents use what controllers
- ensure that if a topic is controller specific that is mentioned in the title
- Have commonly named ans structured topics for covering common material - so for example we might have an APM2.x QuickStart and that would cover the same topics and main areas as the PIxhawk Quick Start. 

I also hope to keep the [Optional Hardware](http://copter.ardupilot.com/wiki/common-optional-hardware/) to be platform agnostic and have separate sections in the document about connecting to different hardware.

Hope that makes sense?

**Comment by lvale** [comment]
I'll copy my initial issue to the other repo.
